# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b95fcef07d8bd5552b8b3234209cdb98367bada7d38e12b7e2216015403d8e507d726bce8fd3eca646a0d3b7bca31e81468307e3d3ce22d2e431da9b46b025c

test:
  secret_key_base: 396cae6216431265f92203895352f220fa080ed354a99201c23fdd6f79a21a25fe6070d7a462415b7d5bb0ce230566166cb89fa6b95fc68f5c21dcd47f1e3607

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
